project_id = "vdzkhealunurfgrujekg"

[functions.nfce-api]
verify_jwt = false

[functions.validate-certificate]
verify_jwt = false

[functions.process-nfce-queue]
verify_jwt = false

[functions.process-nfe-queue]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.fiscal-api]
verify_jwt = false

[functions.nfe-api]
verify_jwt = false

[functions.management-api]
verify_jwt = false

[functions.mdfe-api]
verify_jwt = false

[functions.nfse-api]
verify_jwt = false


[functions.monitoring-snapshot]
verify_jwt = false

[functions.fiscal-cron-tick]
verify_jwt = false

[functions.process-mdfe-queue]
verify_jwt = false

[functions.process-cte-queue]
verify_jwt = false

[functions.process-nfse-queue]
verify_jwt = false

[functions.cte-api]
verify_jwt = false



[functions.migration-export]
verify_jwt = false
