project_id = "vdzkhealunurfgrujekg"

[functions.nfce-api]
verify_jwt = false

[functions.validate-certificate]
verify_jwt = false

[functions.process-nfce-queue]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.fiscal-api]
verify_jwt = false

[functions.nfe-api]
verify_jwt = false

[functions.management-api]
verify_jwt = false
